title: Lauren Zung
author:
  name: Lauren Zung
description: UBC Master of Data Science

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
    social_links:
      github: lzung
      email: laurenzung@gmail.com
      linkedin: lzung
      instagram: l.zung

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
